%YAML 1.2
---

test:
    Debug:
        Level: 3
        DumpConfig: 0
    Config:
        Template: 'prod' # copy config from Prod and overlay Test portion

prod:
    Debug:
        Level: 1
        DumpConfig: 2

    WWW:
        Refresh:
            SunUp: 600
            SunDown: 18000

    General:
        # authoriatize list of timezones: http://www.iana.org/time-zones
        Timezone: 'America/Los_Angeles'
        ImageInterval: 
            # seconds
            SunUp: 30
            SunDown: 90
        MailCommand: "/usr/bin/mail"
        MailRecipient: "nobody@foo.bar"

    GStore:
        ImageBucket: 'image_bucket'
        gsutilPath: '/url/local/bin/gsutil'
        CurrentDir: 'current'
        URL_Prefix: 'http://commondatastorage.googleapis.com/'
        CacheTimeout:
            current_image_50pct.jpg: 600
            current_image_orig.jpg: 600
            blueist_image.jpg: 18000
        PushInterval: 
            # seconds
            SunUp: 570

    Video:
        Daily:
            Name: 'Daily'
            Format: 'orig'
            Compress: True
            # Range is seconds
            Range: 86400
            # ranges are bound by limits
            Limits:
                # allowed terms 'NauticalDawn' and 'NauticalDusk'
                Start: 'NauticalDawn'
                End: 'NauticalDusk'
            URL_file: '/var/www/bib/camera/Daily_url'
            # MediaCategory see https://developers.google.com/youtube/2.0/reference#YouTube_Category_List
            MediaCategory: 'Travel'
            MediaKeyword: 'travel'
            # PublicVideo must be 'allowed' or 'denied'
            PublicVideo: 'allowed'
            # TitleTemplate, TitleTagTemplate, and DescriptionTemplate are python string templates
            # available substitutiions are $date e.g. 2013-09-01
            #                              $underbar_date e.g. 2013_09_01
            #                              $title (obviously don't try and insert $title into the title template, it will fail)
            #                              $video_created
            #                              $video_uploaded - basically now
            TitleTemplate: 'BONGO $date Daily Timelapse'
            TitleTagTemplate: 'BONGO_${date}_Daily_TL'
            DescriptionTemplate: '$title Video created: $video_created, Uploaded: ${video_uploaded}.  Frames are captured at 1920 X 1080.  Time lapse video is approximately 450 times real time.  Video is captured from nautical dawn to nautical dusk.'
        3Hour:
            Name: '3Hour'
            Format: 'orig'
            Compress: False
            Range: 10800
            Limits:
                Start: 'NauticalDawn'
                End: 'NauticalDusk'
            URL_file: '/var/www/bib/camera/3Hour_url'
            MediaCategory: 'Travel'
            MediaKeyword: 'travel'
            PublicVideo: 'allowed'
            TitleTemplate: 'BONGO 6 $date 3 Hour Timelapse'
            TitleTagTemplate: 'BONGO_${date}_3Hour_TL'
            DescriptionTemplate: '$title Video created: $video_created, Uploaded: ${video_uploaded}.  Most recent 3 hours.  Frames are captured at 1920 X 1080 approximately every 30 seconds and then played at 30fps.  Frames are not captured when the sun is > 12degreses below the horizon.'
        
    Image:
        Fetch:
            Command: "/usr/bin/curl"
            FirstArgs: "http://10.1.1.40/jpeg.cgi"
            MiddleArgs: "--user foo:bar --max-time 5"
            FinalArgs: ">"
#            ExtraDebug: "--verbose --trace-time"
            ExtraDebug: ""

    WX:
        RRD_File: "/usr/local/oww/oww.rrd"
        rrdtool: "/usr/bin/rrdtool"
        Dataset:
            Rain: "rain"
        Pressure: 
            ImageFile: "/var/www/bib/camera/pressure.png"
            VLabel: "Pressure (mBar)"
            RRDOtherArgs: "--alt-autoscale"
            DD: "DEF:BP1=/usr/local/oww/oww.rrd:bar1:AVERAGE  LINE1:BP1#0000FF:\"BAR1 Pressure\"  VDEF:lastBP1=BP1,LAST GPRINT:lastBP1:\"%6.1lf mBar\""
        Solar: 
            ImageFile: "/var/www/bib/camera/solar.png"
            VLabel: "Solar"
            RRDOtherArgs: "--lower-limit 0"
            DD: "DEF:SOL1=/usr/local/oww/oww.rrd:solar1:AVERAGE  LINE1:SOL1#0000FF:\"Solar\"  VDEF:lastSOL1=SOL1,LAST GPRINT:lastSOL1:\"%6.1lf \""
        Dir: 
            ImageFile: "/var/www/bib/camera/dir.png"
            VLabel: "Wind Direction"
            RRDOtherArgs: "--rigid --upper-limit 360 --lower-limit 0"
            DD: "DEF:WDE=/usr/local/oww/oww.rrd:weast:AVERAGE DEF:WDN=/usr/local/oww/oww.rrd:wnorth:AVERAGE CDEF:AWD=90,WDN,WDE,ATAN2,RAD2DEG,-,DUP,0,LT,360,0,IF,+  VDEF:lastAWD=AWD,LAST LINE2:AWD#880000:\"Wind direction\" GPRINT:lastAWD:\"%6.1lf deg\""
        Wsp: 
            ImageFile: "/var/www/bib/camera/wsp.png"
            VLabel: "Wind Spd/Gust (mph)"
            RRDOtherArgs: "--lower-limit 0"
            DD: "DEF:WS=/usr/local/oww/oww.rrd:wspd:AVERAGE  LINE1:WS#0000FF:\"Wind Speed\"  DEF:GU=/usr/local/oww/oww.rrd:gust:AVERAGE  LINE1:GU#880000:\"Wind Gust\"  VDEF:lastWS=WS,LAST GPRINT:lastWS:\"%6.1lf mph\"  VDEF:lastGU=GU,LAST GPRINT:lastGU:\"%6.1lf mph\""
        TDW: 
            ImageFile: "/var/www/bib/camera/tdw.png"
            VLabel: "Temp, Dp, Wc (F)"
            DD: "DEF:WC=/usr/local/oww/oww.rrd:wchl:AVERAGE  LINE1:WC#0000FF:\"Wind Chill\"  DEF:TH1=/usr/local/oww/oww.rrd:thmp1:AVERAGE  LINE1:TH1#FF00FF:\"Mast\"  DEF:DP1=/usr/local/oww/oww.rrd:dp1:AVERAGE  LINE1:DP1#000000:\"Dew Point\"  VDEF:lastWC=WC,LAST GPRINT:lastWC:\"%6.1lf F\"  VDEF:lastTH1=TH1,LAST GPRINT:lastTH1:\"%6.1lf F\"  VDEF:lastDP1=DP1,LAST GPRINT:lastDP1:\"%6.1lf F\""
        Rain: 
            ImageFile: "/var/www/bib/camera/rain.png"
            VLabel: "Rain (inches)"
            RRDOtherArgs: "--lower-limit 0"
            DD: "DEF:RAIN=/usr/local/oww/oww.rrd:rain:AVERAGE  LINE1:RAIN#FF0000:\"Rain            \"  DEF:DRN=/usr/local/oww/oww.rrd:rainint:AVERAGE  LINE1:DRN#00FF00:\"Rain Int        \"  DEF:RRN=/usr/local/oww/oww.rrd:rainrate:AVERAGE  LINE1:RRN#0000FF:\"Rain Rate \"  VDEF:lastRAIN=RAIN,LAST GPRINT:lastRAIN:\"%6.2lf \"  VDEF:lastDRN=DRN,LAST GPRINT:lastDRN:\"%6.2lf \"  VDEF:lastRRN=RRN,LAST GPRINT:lastRRN:\"%6.2lf \""
        
    Sun:
        Lat: '47.00'
        Long: '-122.0'
        Iteration: '0'
        AngleNautical: '-12'
        AngleCivil: '-6'
        AngleHorizon: '0'

    Directories:
      cam_images:
        test: /usr/local/cam/data/cam_images_test/
        prod: /usr/local/cam/data/cam_images/
      video:
        test: /usr/local/cam/data/video/
        prod: /usr/local/cam/data/video/
      www:
        test: /var/www/bib/camera/
        prod: /var/www/bib/camera/

    Bins:
        push2youtube: "/usr/local/cam/bin/push2youtube.py"
        push2youtube_args: "--doDeletes"
	ffmpeg: "ffmpeg"

    FPS: 15
    Type: jpg
    FFMpegLogLevel: error
    DescriptionText: 'Frames are captured at 1920 X 1080.  Time lapse video is approximately 450 times real time.  Video is captured from nautical dawn to nautical dusk.'

    BlueCode:
        File: "bluecode"
        BlueistImage: "blueist_image.jpg"
        PrimingValue: -1000
        Sampling: 2
        CodeScaling: .25
        BlueTest:
            StartRow: 0
            Rows: 400

    Overlay:
        Clock:
            Overlay: True
            # values are left, right, or a number that represents the % from left to right
            XLocation: 100
            # values are top, bottom, or a number that represents the % from top to bottom
            YLocation: 100
            XBorder: 10
            YBorder: 10
            Width: 125
            Height: 125
            FGColor: "blue"
            BGColor: "black"
            LineWeight: 4
            WriteImage: False
            ImageFile: "/var/www/bib/camera/clock.jpg"
        WX:
            Overlay: False
            # values are left, right, or a number that represents the % from left to right
            XLocation: left
            # values are top, bottom, or a number that represents the % from top to bottom
            YLocation: 100
            XBorder: 10
            YBorder: 10
            Width: 1920
            Height: 100
            IndividualWidth: 1920
            IndividualHeight: 100
            FGColor: "paleblue"
            BGColor: "black"
            XColor: "white"
            LumColor: "yellow"
            BarGutter: 4
            WriteImage: True
            ImageFile: "/var/www/bib/camera/wx.jpg"
        ColorGraph:
            Overlay: False
            # values are left, right, or a number that represents the % from left to right
            XLocation: left
            # values are top, bottom, or a number that represents the % from top to bottom
            YLocation: 50
            XBorder: 10
            YBorder: 10
            Width: 1000
            Height: 300
            FGColor: "paleblue"
            BGColor: "black"
            XColor: "white"
            LumColor: "yellow"
            BarGutter: 4
            WriteImage: True
            ImageFile: "/var/www/bib/camera/color_graph.jpg"
        
    Sizes:
      qfull:
        width: 1920
        height: 1376
      orig:
        width: 1920
        height: 1080
      1080p:
        width: 1920
        height: 1080
      2048w:
        width: 2048
        height: 1152
      50pct:
        width: 960
        height: 688
...
