%YAML 1.2
---

Root1:
    Google:
        YT:
            dev_key: "sekrit"
            client_id: "client_id"
            service_email: "foo@bar.com"
            service_password: "sekrit"
            service_source: "service_source"
    Paths:
        video_file: "/usr/local/cam/data/video/output_orig.mp4"
# remove this when we stop useing push2youtube with push2youtube_2015
prod:
    Google:
        Auth:
            client_secrets_file: ""
            oauth_token_file: ""
            api_key: ""  # for public requests
    Paths:
        video_file: "/usr/local/cam/data/video/output_orig.mp4"
    Url: 
        pre: "https://www.youtube.com/v/"
test:
    Google:
        Auth:
            client_secrets_file: ""
            oauth_token_file: ""
            api_key: ""  # for public requests
    Paths:
        video_file: "/usr/local/cam/data/video/output_orig-test.mp4"
    Url: 
        pre: "https://www.youtube.com/v/"
...
